site:
  title: My Antora Site
  start_page: my-component::index.adoc

content:
  sources:
    - url: .
      branches: main

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/archive/main/antora-ui-default-main.zip
    snapshot: true

output:
  dir: ./public
